//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisaabManagement.Datalayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class managementEntities : DbContext
    {
        public managementEntities()
            : base("name=managementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblmembermaster> tblmembermasters { get; set; }
        public DbSet<tbltransactionmaster> tbltransactionmasters { get; set; }
        public DbSet<tbltransactiontype> tbltransactiontypes { get; set; }
    }
}
