//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisaabManagement.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltransactionmaster
    {
        public long id { get; set; }
        public long transactionfrom { get; set; }
        public long transactionto { get; set; }
        public int transactiontype { get; set; }
        public decimal credit { get; set; }
        public decimal debit { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> transactiondate { get; set; }
    }
}
